d/postinst: add snippet to manage systemd-tmpfiles
Copy over manually as we do not use a #DEBHELPER# stanza here.

Suggested-by: Fabian Gründbichler <f.gruenbichler@proxmox.com>
Signed-off-by: Thomas Lamprecht <t.lamprecht@proxmox.com>

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -133,6 +133,13 @@ migrate_apt_auth_conf() {
     fi
 }
 
+# Copied from dh_installtmpfiles/13.24.2
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+       if [ -x "$(command -v systemd-tmpfiles)" ]; then
+               systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create pve-manager.conf || true
+       fi
+fi
+
 case "$1" in
   triggered)
     # We don't print a status message here, as dpkg already said
